version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pulse-server
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUD_NAME}
      CLOUDINARY_API_KEY: ${API_KEY}
      CLOUDINARY_API_SECRET: ${API_SECRET}
      CHOKIDAR_USEPOLLING: "true"
    command: npm run dev
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pulse-client
    ports:
      - "5173:80"
    depends_on:
      - server
